### ISSUE TITLE
What is Umbraco primarily used for?

### ISSUE THREAD

**Issue by garrytrinder** [mattbrailsford/ama#1]
Is it just a CMS? Or can it be used as a base for creating applications?

**Comment by mattbrailsford** [comment]
A great first question :)

Umbraco is pitched as a CMS yes, but it's flexibility allows it to be used for many other scenarios. One of Umbraco's core concepts from the very beginning, that we are seeing more and more in newer frameworks, is the definition of a "document type" which is a type of schema for you content, which allows you to define a bespoke content editing experience for your exact requirements. Where other systems would force you to fit into their vision of how content management should work, Umbraco has always believed that the editor experience should fit your needs, not the other way round.

In addition, Umbraco has a whole heap of extension points built in, allowing you to hook into almost every action the system performs allowing you to react to and modify it's behavior.

Teamed together, these two elements allow you to do a lot more than just manage website content. It effectively makes it a CMW, Content Management Whatever :)
