### ISSUE TITLE
How much planning do you do you before starting on a project ?

### ISSUE THREAD

**Issue by ravimotha** [mattbrailsford/ama#10]
Do you have an idea and then see how it works and then refine or do you have a definite start and end points ?

and how do handle decisions that change the path of something you are doing? you are trying to developa solution and you release there may be 2 ways of doing something do you stop and see which is better/more extensible has more options or do you pick a path and no tworry about the other?

**Comment by mattbrailsford** [comment]
Not sure if you mean Umbraco, or hardware, but I guess my approach is much the same.

I very much code and hack in a "discovery" kinda of way, so I'll spend little time actually planning, instead I'll investigate by actually doing (coding or hacking) and refine as I go along. I'll probably break down in my head what I perceive to be basic areas of the project and then focus on building one area. As I work, I'll generally start to see patterns of repetition, or think that something could be done better, or more cleanly and so I'll refactor. For code this is easy, but for hardware this generally means spending more money on some new components :)

When it comes to deciding between two similar options, I very much suffer from "analysis paralysis" and struggle to choose a route. It's especially hard when you are a sole dev/maker as you don't have anyone immediately to hand to ask advise (skype comes in handy, but more often than not, you are just distracting the other person from what they need to be doing, so it's hard). Usually though, I'll just force myself down what I think to be the best path (or just choose one) and get moving. If I hit a problem, and realize the other option would have been a better choice, I'll often refactor, even if it means spending more time on it than i should (only really affects paid coding gigs that though).
