### ISSUE TITLE
Which package you wish you came up with

### ISSUE THREAD

**Issue by dawoe** [mattbrailsford/ama#12]
You created numerous packages, but is there a package that makes you think : I wish I came up with that idea ?

**Comment by mattbrailsford** [comment]
I really wish I'd come up with UI-O-Matic as I think it's an awesome package. I helped contribute with the v2 build, but I still think there is a bunch of things that could be done to make it even better (which I'd love to work on if I had the time).

I guess that's the thing with open source packages, if you find a package you'd wished you came up with you can always contribute to it and make it better. I think that is generally how my mind works. I may not always come with unique ideas myself, but when I see another idea, I think of how it could be taken to the next level.

A few closed source packages I'd love to get involved in would be Umbraco Forms (general cleanup) and TeaCommerce (I think this is the most "umbraco" ecommerce platform, I just wish it was OSS), 

Fun fact, you may not know this, but @LeeKelleher and I did create our own grid called Mortar before Umbraco came out with theirs. We were just about to launch it when the core Grid came out so we decided not to bother. It did lead us to create Doc Type Grid Editor though, the killer feature our grid had but the core grid didn't, and also lead to Nested Content, so we can't complain :)

**Comment by dawoe** [comment]
LOL..sounds familiar...I was working on package called "Inline Content"...but suddenly something was released called "Nested Content"

**Comment by mattbrailsford** [comment]
Sorry :)

**Comment by leekelleher** [comment]
@dawoe ...but did it use doctypes? 😉 

@mattbrailsford I love those packages that grow organically.

**Comment by mattbrailsford** [comment]
@leekelleher absolutely. We were gutted we missed out on releasing Mortar, but look what came out of it, IMO a much more useful editor.

**Comment by dawoe** [comment]
@leekelleher yes it did ! Was trying to build a alternative for Archetype
