### ISSUE TITLE
Age and other stats

### ISSUE THREAD

**Issue by sotirisf** [mattbrailsford/ama#5]
How old are you?
When did you first start working with Umbraco?
What CMS (or other platform/technology) did you work with BEFORE Umbraco?
What other platforms/technologies are you currently working with?

**Comment by mattbrailsford** [comment]
1. 37
2. I think it was around 2010 back on v4.5
3. I was EPIServer certified :)
4. I've been getting into a JS framework of late called VueJS which looks really cool, but I've only managed to use it a couple of times. I do keep my eye on the CMS landscape though with interest in platforms such as Prismic, Wagtail CMS and recently Kentico Cloud.
