### ISSUE TITLE
Alternative career path?

### ISSUE THREAD

**Issue by karltynan** [mattbrailsford/ama#9]
Hey Matt,

Not sure what you have studied or your route into code, but if you weren't doing what you do today, what would you be doing instead?

Thanks,
Karl

**Comment by mattbrailsford** [comment]
I've looked back at my career quite a few times and I can't say I've ever really sat down and thought "what do I want to do", instead I've generally followed the path of "what am I good at" so even from college / uni I've always been headed down this route. 

At school I was pretty good in the IT class and enjoyed art, then moved into graphic design at college and then moved into multimedia design at uni which married the two, however working in the industry, I found the design perspective to be too subjective so focused more on the development side of things which is more cut an dry "does it work, or doesn't it" :)

That said, I do wish I was doing more with my hands, so I'd love to get into carpentry or something similar (which is maybe we I enjoy making as my hobby).
